### ISSUE TITLE
There is no csproj

### ISSUE THREAD

**Issue by Cyl18** [Kayzwer/yolo-cs#2]

**Comment by Kayzwer** [comment]
I just make it into a directory and import it from main (in this case, your Program.cs)

**Comment by Cyl18** [comment]
i mean it's time consuming to import all the nuget packages, if there's a csproj file it'd be better

**Comment by Kayzwer** [comment]
> i mean it's time consuming to import all the nuget packages, if there's a csproj file it'd be better

how about you make one, and then I merge your PR (not really a pro in C#)
