### ISSUE TITLE
YOLO V10 support

### ISSUE THREAD

**Issue by cjhawes** [Kayzwer/yolo-cs#3]
YOLO V10 was announced by ultralytics on the 25th of May. Are there any plans to support this?

https://arxiv.org/pdf/2405.14458
https://docs.ultralytics.com/models/yolov10
https://github.com/THU-MIG/yolov10

**Comment by Kayzwer** [comment]
> YOLO V10 was announced by ultralytics on the 25th of May. Are there any plans to support this?
> 
> https://arxiv.org/pdf/2405.14458
> https://docs.ultralytics.com/models/yolov10
> https://github.com/THU-MIG/yolov10

https://github.com/ivilson/Yolov7net
this repo can help
